# This is a basic workflow to help you get started with Actions

name: Generate Index

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Fetch MessengerData
      run: |
        git clone --depth 1 https://github.com/AnonyKagamine/MessengerData
        find MessengerData | grep -E '\.json$'
      
    - name: Fetch MDI
      run: |
        git clone --depth 1 https://github.com/AnonyKagamine/MessengerDataIndex
      
    - name: Generate Index
      run: |
        find MessengerData | grep -E '\.json$' | python3 MessengerDataIndex/generate_index.py
        cp index.json MessengerDataIndex/
    - name: Commit Local Changes
      env:
        GIT_USER: 'Anony Kagamine'
        GIT_EMAIL: '16967744+AnonyKagamine@users.noreply.github.com'
      run: |
        cd MessengerDataIndex/
        git config --global user.email $GIT_EMAIL
        git config --global user.name $GIT_USER
        git add .
        git commit -m "Auto-generate new index" -a
        cd ..
    
    - name: Push to MDI Repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GITHUB_API_TOKEN }}
        repository: 'AnonyKagamine/MessengerDataIndex'
        directory: 'MessengerDataIndex' 
